platform :ios, '8.0'
inhibit_all_warnings!

target 'FitCloudDemo' do
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'TPKeyboardAvoiding', '~> 1.3.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'DateTools', '~> 1.7.0'
pod 'NSLogger', '~> 1.5.1'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'YYModel', '~> 1.0.4'
pod 'KVOController'
end