//
//  FitCloudUtils.h
//  FitCloud
//
//  Created by 远征 马 on 2016/11/7.
//  Copyright © 2016年 马远征. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "FitCloudBlock.h"


/*!
 * @class FitCloudUtils
 * @discussion This class is mainly used for data analysis, type conversion and so on
 */
@interface FitCloudUtils : NSObject

#pragma mark - Day Total Data
/*!
 Day total data will be analyzed into the total number of steps, total distance, total calories, deep sleep duration, light sleep duration, average heart rate

 @param data Day total data
 @param block Callback block
 @return if data is <i>nil</i>,return <i>NO</i>
 */
+ (BOOL)resolveDayTotalData:(NSData*)data withCallBackBlock:(FCDayTotalDataBlock)block;


#pragma mark - System Settings
/*!
 The system setting data is divided into detailed setting data

 @param data system setting data
 @param block The resulting callback block
 @return if data is <i>nil</i>,return <i>NO</i>
 */
+ (BOOL)resolveSystemSettingsData:(NSData*)data withCallbackBlock:(FCSystemSettingDataBlock)block;


#pragma mark - Firmware Version
/*!
 Divide the hardware and software version information data into detailed data

 @param data hardware and software version information data
 @param block The resulting callback block
 @return if data is <i>nil</i>,return <i>NO</i>
 */
+ (BOOL)resolveHardwareAndSoftwareVersionDataToString:(NSData*)data withCallbackBlock:(FCHardwareAndSoftwareVersionStringBlock)block;


/*!
 Divide the hardware and software version information data into detailed data and parse the detailed data into strings

 @param data hardware and software version information data
 @param block The resulting callback block
 @return if data is <i>nil</i>,return <i>NO</i>
 */
+ (BOOL)resolveHardwareAndSoftwareVersionData:(NSData*)data withCallbackBlock:(FCHardwareAndSoftwareVersionDataBlock)block;


#pragma mark - calorie and distance
/*!
 Calculate calories consumed by exercise

 @param stepCount Number of steps
 @return calorie in Kcal
 */
+ (NSNumber*)calorieWithStepCount:(NSNumber*)stepCount;


/*!
 The walking distance is calculated according to the number of steps

 @param stepCount Number of steps
 @return Movement distance in kilometers
 */
+ (NSNumber*)distanceWithStepCount:(NSNumber*)stepCount;


#pragma mark - Exerciese
/*!
 Convert sports data to an array containing dictionary objects,Each record contains five minutes of data

 @param data The sports data to be converted
 @return a list of <code>NSDictionary</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveExerciseDataIntoDictionaryObjects:(NSData*)data;


/*!
 Convert sports data to an array containing dictionary objects,Each record contains five minutes of data
 
 @param data The sports data to be converted
 @return a list of <code>FCExerciseModel</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveExerciseDataIntoModelObjects:(NSData*)data;


#pragma mark - Sleep
/*!
 Convert sleep data to an array containing dictionary objects,Each record contains five minutes of data
 
 @param data The sleep data to be converted
 @return a list of <code>NSDictionary</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveSleepDataIntoDictionaryObjects:(NSData*)data;


/*!
 Convert sleep data to an array containing the model objects,Each record contains five minutes of data
 
 @param data The sleep data to be converted
 @return a list of <code>FCSleepModel</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveSleepDataIntoModelObjects:(NSData*)data;


#pragma mark - Health
/*!
 Convert heart rate data to an array containing dictionary objects,Each record contains five minutes of data
 
 @param data The heart rate data to be converted
 @return a list of <code>NSDictionary</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveHeartRateDataIntoDictionaryObjects:(NSData*)data;


/*!
 Convert heart rate data to an array containing the model objects,Each record contains five minutes of data
 
 @param data The heart rate data to be converted
 @return a list of <code>FCHealthModel</code> objects
 @warning If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (NSArray*)resolveHeartRateDataIntoModelObjects:(NSData*)data;


/*!
 Health data including blood oxygen, blood oxygen, and respiratory rate are generated by heart rate data modeling

 @param data Heart rate data
 @param block Callback several different types of health data
 @param systolicBP Default systolic pressure
 @param diastolicBP Default diastolic pressure
 @return If the parameter is <i>nil</i>, returns <i>nil</i>
 */
+ (BOOL)resolveHeathDataIntoModelObjects:(NSData*)data systolic:(UInt16)systolicBP diastolic:(UInt16)diastolicBP withCallbackBlock:(FCHealthDataModelBlock)block;

@end


#pragma mark - NSData Extention
/*!
 * @category NSData
 * @discussion NSData class method extension
 */
@interface NSData (Utils)

/*!
 Converts system settings data to a data model with detailed attributes

 @return The object to be converted
 @warning if self is <i>nil</i>, return <i>nil</i>
 */
- (id)objectFromSystemSettingsData;


/*!
 Converts system settings data to a dictonary with detailed data
 
 @return The object to be converted
 @warning if self is <i>nil</i>, return <i>nil</i>
 */
- (NSDictionary*)dictionaryFromSystemSettingsData;


/*!
 Converts hardware and software version information data to a dictionary with detailed data

 @return The object to be converted
 @warning if self is <i>nil</i>, return <i>nil</i>
 */
- (NSDictionary*)dictionaryFromSoftwareAndHardwareVersionData;
@end



#pragma mark - NSArray Extention
/*!
 * @category NSArray
 * @discussion NSArray class method extension
 */
@interface NSArray (Utils)

/*!
 Convert alarm clock data to alarm clock models

 @param data The alarm clock data to be converted
 @return a list of <code>FCAlarmObject</code> objects, if data is <i>nil</i>,return nil.
 */
+ (NSArray*)arrayWithAlarmClockConfigurationData:(NSData*)data;


/*!
 Combines a set of alarm clock models into alarm clock data

 @return Alarm clock data according to Bluetooth protocol standard
 */
- (NSData*)alarmClockConfigurationData;
@end


#pragma mark - NSNumber

@interface NSNumber (Utils)

/*!
 手机的型号，用于登录和绑定设备时手表识别不同型号的机型

 @return 手机机型对应的数值
 */
+ (NSNumber*)phoneModel;


/*!
 手机操作系统型号，用于手表区分不同的系统

 @return 操作系统对应的数值
 */
+ (NSNumber*)osType;
@end
