//
//  FCConstants.m
//  FitCloud
//
//  Created by 远征 马 on 16/9/5.
//  Copyright © 2016年 远征 马. All rights reserved.
//

#import "FCConstants.h"

NSString *const EVENT_CENTRALMANAGER_UPDATE_STATE_NOTIFY = @"EVENT_CENTRALMANAGER_UPDATE_STATE_NOTIFY";
NSString *const EVENT_CONNECT_PERIPHERAL_NOTIFY = @"EVENT_CONNECT_PERIPHERAL_NOTIFY";
NSString *const EVENT_FAIL_CONNECT_PERIPHERAL_NOTIFY = @"EVENT_FAIL_CONNECT_PERIPHERAL_NOTIFY";
NSString *const EVENT_DISCONNECT_PERIPHERAL_NOTIFY = @"EVENT_DISCONNECT_PERIPHERAL_NOTIFY";
NSString *const EVENT_DISCOVER_CHARACTERISTICS_NOTIFY = @"EVENT_DISCOVER_CHARACTERISTICS_NOTIFY";
// 固件升级断开连接通知
NSString *const EVENT_FIRMWARE_UPDATE_DISCONNECT_PERIPHERAL_NOTIFY = @"EVENT_FIRMWARE_UPDATE_DISCONNECT_PERIPHERAL_NOTIFY";
